---
- name: Get current {{ domain }} VM attached disk count
  become: true
  become_user: root
  ansible.builtin.shell: "virsh dumpxml {{ domain }} | grep \"source file='{{ ocp_storage_data_dir }}/{{ domain }}/local_storage_disk\" | wc -l"
  register: cur_storage_disks

- name: Change {{ domain }} VM specs
  become: true
  become_user: root
  when: (cur_storage_disks.stdout | int) > 0
  block:
    - name: Clear host VM memory cache
      ansible.builtin.shell: echo 3 | tee /proc/sys/vm/drop_caches
    - name: Detach data disks from {{ domain }} VM
      ansible.builtin.command: "virsh detach-disk {{ domain }} --target {{ disk }} --persistent"
      ignore_errors: true
      loop: "{{ ocp_storage_data_disks }}"
      loop_control:
        index_var: index
        loop_var: disk

    - name: Destroy local storage data disks for {{ domain }} VM
      ansible.builtin.file:
        state: absent
        path: "{{ ocp_storage_data_dir }}/{{ domain }}/local_storage_disk_{{ index + 1 }}"
      loop: "{{ ocp_storage_data_disks }}"
      loop_control:
        index_var: index
        loop_var: disk

- name: Stop {{ domain }} VM
  community.libvirt.virt:
    name: "{{ domain }}"
    state: destroyed

- name: Start {{ domain }} VM
  community.libvirt.virt:
    name: "{{ domain }}"
    state: running
