---
- name: Get current {{ domain }} VM attached disk count
  become: true
  become_user: root
  shell: "virsh dumpxml {{ domain }} | grep \"source file='{{ local_storage_data_dir }}/{{ domain }}/local_storage_disk\" | wc -l"
  register: cur_storage_disks

- name: Change {{ domain }} VM specs
  become: true
  become_user: root
  when: (cur_storage_disks.stdout | int) > 0
  block:

  - name: Clear host VM memory cache
    shell: echo 3 | tee /proc/sys/vm/drop_caches

  - name: Detach data disks from {{ domain }} VM
    command: "virsh detach-disk {{ domain }} --target {{ disk }} --persistent"
    ignore_errors: yes
    loop: "{{ local_storage_disks }}"
    loop_control:
      index_var: index
      loop_var: disk

  - name: Destroy local storage data disks for {{ domain }} VM
    file:
      state: absent
      path: "{{ local_storage_data_dir }}/{{ domain }}/local_storage_disk_{{ index + 1 }}"
    loop: "{{ local_storage_disks }}"
    loop_control:
      index_var: index
      loop_var: disk

- name: Stop {{ domain }} VM
  virt:
    name: "{{ domain }}"
    state: destroyed
