apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-image-registry-pvc
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi 
