heat_template_version: 2015-04-30

parameters:
  servers:
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol.
    type: json

resources:
  CustomPostConfigOvnCheck:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        # This script will only execute on the node
        # where the 'ovn-dbs-bundle-0' container is running.
        if sudo podman ps --format '{{.Names}}' | grep -q '^ovn-dbs-bundle-podman-0$'; then
          echo "Running post-deployment ovn check on the ovn-dbs-bundle-podman-0 node." >> /var/log/post_ovn_check_script.log
          # Explicitly check if the service is "not running"
          if sudo pcs status | grep -q "ovn-dbs-bundle.*not running"; then
            echo "OVN DBS bundle is 'not running'. Attempting to restart." >> /var/log/post_ovn_check_script.log
            # Try to restart the service. The script's exit code will be determined by this command's success or failure.
            sudo pcs resource restart ovn-dbs-bundle
          else
            echo "OVN DBS bundle is running correctly. No action needed." >> /var/log/post_ovn_check_script.log
            # If the service is fine, we do nothing and the script will exit 0.
          fi
        fi

  MyPostDeployments:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers: {get_param: servers}
      config: {get_resource: CustomPostConfigOvnCheck}
      actions:
        - CREATE
        - UPDATE
