osp_release_defaults:
  vmset:
    Controller:
      # Reset default Controller roleCount to 0
      count: 0
    CtlNovaStdalone:
      count: 1
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
    Novacontrol:
      count: 1
      cores: 2
      memory: 10
      networks:
        - ctlplane
        - internal_api
        - storage
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
