osp_release_defaults: {}
# TODO: remove once we have a 16.2.2 tripleoclient image that includes ipa-client
openstackclient_image: docker-registry.upshift.redhat.com/openstack-k8s-operators/openstack-tripleoclient:16.2_ipa_client
