---
enable_fencing: true

ocp_master_memory: 50000
ocp_master_vcpu: 12
ocp_num_workers: 0
ocp_worker_memory: 20000
ocp_worker_disk: 20

osp_release_defaults:
  vmset:
    Controller:
      count: 3
      cores: 6
      memory: 30
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
      additional_disks:
        - name: datadisk
          disk_size: 1
          storage_class: host-nfs-storageclass
          storage_access_mode: ReadWriteMany
          storage_volume_mode: Filesystem

workaround_jira18571: true
