enable_freeipa: true

osp_release_defaults:
  tlse: true
  networks: ipv4_subnet
  vmset:
    Controller:
      # Reset default Controller roleCount to 0
      count: 0
    CtlNovaStdalone:
      count: 1
      cores: 6
      disk_size: 40
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      storage_class: host-nfs-storageclass
    Novacontrol:
      count: 1
      cores: 2
      disk_size: 40
      memory: 10
      networks:
        - ctlplane
        - internal_api
        - storage
      storage_class: host-nfs-storageclass
