openstackclient_image: registry.redhat.io/rhosp-rhel8/openstack-tripleoclient:16.2
osp_rhos_release_compose: passed_phase2
osp:
  release: 16.2
  # OSP controller VM sizing
  controller:
    count: 1
    cores: 6
    memory: 20
    disk_size: 40
    # use http://download.devel.redhat.com to get the local mirror depending on where the server is
    base_image_url: http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/8.4/1168/images/rhel-guest-image-8.4-1168.x86_64.qcow2
    storage_class: host-nfs-storageclass
  # OSP compute OCP worker settings
  compute:
    # number of OCP worker nodes should be OSP compute hosts
    count: 2
    # if false nfs is used for glance
    hci: false
    # number of OSD disks per compute node
    ceph_osd_disks:
      - sdb
      - sdc
    # size of OSD disk size in GB
    ceph_num_osd_disk_size: 20
  networks:
    ctlplane:
      cidr: 192.168.25.0/24
      gateway: 192.168.25.1
      allocation:
        start: 192.168.25.100
        end: 192.168.25.250
      attach_config:
        bridge_name: br-osp
        interface: enp7s0
    internalapi:
      cidr: 172.17.0.0/24
      vlan: 20
      allocation:
        start: 172.17.0.10
        end: 172.17.0.250
      attach_config:
        bridge_name: br-osp
        interface: enp7s0
    external:
      cidr: 10.0.0.0/24
      gateway: 10.0.0.1
      allocation:
        start: 10.0.0.10
        end: 10.0.0.250
      attach_config:
        bridge_name: br-ex
        interface: enp6s0
    storage:
      cidr: 172.18.0.0/24
      vlan: 30
      allocation:
        start: 172.18.0.10
        end: 172.18.0.250
      attach_config:
        bridge_name: br-osp
        interface: enp7s0
    storagemgmt:
      cidr: 172.19.0.0/24
      vlan: 40
      allocation:
        start: 172.19.0.10
        end: 172.19.0.250
      attach_config:
        bridge_name: br-osp
        interface: enp7s0
    tenant:
      cidr: 172.20.0.0/24
      vlan: 50
      allocation:
        start: 172.20.0.10
        end: 172.20.0.250
      attach_config:
        bridge_name: br-osp
        interface: enp7s0
  container_tag: 16.2_20210901.2
  ceph_image: rhceph
  ceph_tag: 5-12
  # OSP deployment timeout
  deploy_timeout: 60m
