---
osp_release_auto_version: 17.0-RHEL-9
osp_release_auto_compose: passed_phase2

osp_release_defaults:
  base_image_url: http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/9.0/20220428.0/images/rhel-guest-image-9.0-20220428.0.x86_64.qcow2
  networks: ipv6_subnet
  vmset:
    Controller:
      count: 1
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
  bmset:
    Compute:
      count: 0
    ComputeLeaf1:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf1
        - tenant_leaf1
        - storage_leaf1
    ComputeLeaf2:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf2
        - tenant_leaf2
        - storage_leaf2
  extrafeatures:
    - ipv6


ephemeral_heat:
  heat_api_image: quay.io/tripleowallaby/openstack-heat-api:current-tripleo
  heat_engine_image: quay.io/tripleowallaby/openstack-heat-engine:current-tripleo
  mariadb_image: quay.io/tripleowallaby/openstack-mariadb:current-tripleo
  rabbit_image: quay.io/tripleowallaby/openstack-rabbitmq:current-tripleo

# phase2 tempest tests
tempest_test_dict:
  regex: '(?!.*\[.*\bslow\b.*\])(^tempest\.(api|scenario))'
  includelist: []
  # per default with OVN there is no DHCPAgent, disable the tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON tests
  excludelist:
      - "^tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_block_migration_paused"
      - "^tempest.api.compute.admin.test_live_migration.LiveAutoBlockMigrationV225Test.test_live_block_migration_paused"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationRemoteConsolesV26Test.test_live_block_migration_paused"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp"


tempest_enable_feature_dict:
  network:
    # The cidr block to allocate project ipv6 subnets from (string value)
    project_network_v6_cidr: 2001:db8:fd01::/48
  compute-feature-enabled:
    vnc_console: true
    live_migration: true
    block_migration_for_live_migration: true
    volume_backed_live_migration: true
    console_output: true
