---
# this address needs to be reachable from IPMI/iDRAC if BM worker is used 
ocp_ai_discovery_iso_server: 192.168.111.1

ocp_ai_external_dns:
  - 10.11.5.19
  - 10.38.5.26
  - 10.10.160.2
  - 10.5.30.160

# ocp_ai_ansible_repo: defaults to "https://github.com/openstack-k8s-operators/crucible.git"
# ocp_ai_ansible_branch: defaults to "f32b46317e5bb25fffe16c93fdc0f87a72d423bf"

ocp_ai_bm_bridge_master_mac_prefix: 3c:fd:fe:78:ab:0
ocp_ai_bm_bridge_worker_mac_prefix: 3c:fd:fe:78:ab:1
ocp_ai_prov_bridge_master_mac_prefix: 3c:fd:fe:78:cd:0
ocp_ai_prov_bridge_worker_mac_prefix: 3c:fd:fe:78:cd:1

# ocp_ai_sushy_port: defaults to "8082"

ocp_ai_libvirt_storage_dir: /var/lib/libvirt/images

# Pin aicli to a version that uses AI API v1 by default, as this is the API version
# that Crucible uses for the time being
ocp_ai_cli_version: "99.0.202112021829.202103111306"
