---
ocp_ai_discovery_iso: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-live.x86_64.iso

ocp_ai_external_dns:
  - 10.11.5.19
  - 10.38.5.26
  - 10.10.160.2
  - 10.5.30.160

# ocp_ai_service_repo: defaults to "https://github.com/sonofspike/assisted-service-onprem.git"
# ocp_ai_service_branch: defaults to "a55b218e3176ed920200c1283256337db94ae4b6"
# ocp_ai_ansible_repo: defaults to "https://github.com/sonofspike/cluster_mgnt_roles.git"
# ocp_ai_ansible_branch: defaults to "9051f7da86fa90f9b60c1b09414dabeaf7d58fb7"

ocp_ai_bm_bridge_master_mac_prefix: 3c:fd:fe:78:ab:0
ocp_ai_bm_bridge_worker_mac_prefix: 3c:fd:fe:78:ab:1
ocp_ai_prov_bridge_master_mac_prefix: 3c:fd:fe:78:cd:0
ocp_ai_prov_bridge_worker_mac_prefix: 3c:fd:fe:78:cd:1

ocp_ai_bm_bridge_cidr: 192.168.111.0/24 # NOTE: Must currently end in /24
ocp_ai_bm_bridge_dhcp_range: 192.168.111.6,192.168.111.100 # NOTE: Must leave .2, .3 and .4 outside the range
ocp_ai_pr_bridge_cidr: 172.22.0.0/24 # NOTE: Must currently end in /24
ocp_ai_pr_bridge_dhcp_range: 172.22.0.10,172.22.0.254
ocp_ai_bm_ip: "{{ (ocp_ai_bm_bridge_cidr.split('.')[0:3]|join('.')) }}.1"
ocp_ai_pr_ip: "{{ (ocp_ai_pr_bridge_cidr.split('.')[0:3]|join('.')) }}.1"

# ocp_ai_sushy_port: defaults to "8082"

# ocp_ai_service_store_dir: defaults to "/opt/assisted-service"
# ocp_ai_service_port: defaults to "8090"

# ocp_ai_http_store_dir: defaults to "/opt/http_store/data"
# ocp_ai_http_store_port: defaults to "8081"

ocp_ai_libvirt_storage_dir: /var/lib/libvirt/images
