# Todo: need to check what is missing in upstream wallaby tripleoclient image
# openstackclient_image: quay.io/tripleowallaby/openstack-tripleoclient:current-tripleo
openstackclient_image: quay.io/openstack-k8s-operators/tripleowallaby-openstack-tripleoclient:current-tripleo_patched
osp_release_defaults:
  release: wallaby
  container_tag: current-tripleo
  base_image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow2
  #TODO: which ceph images tag to use for upstream train?
  #ceph_tag: 5-12
  #ceph_image: daemon
ephemeral_heat:
  heat_api_image: quay.io/tripleowallaby/openstack-heat-api:current-tripleo
  heat_engine_image: quay.io/tripleowallaby/openstack-heat-engine:current-tripleo
  mariadb_image: quay.io/tripleowallaby/openstack-mariadb:current-tripleo
  rabbit_image: quay.io/tripleowallaby/openstack-rabbitmq:current-tripleo

