---
- name: Set directory for "{{ name }}" yaml files
  set_fact:
    "{{ name }}_yaml_dir": "{{ working_yamls_dir }}/{{ name }}"
    __yaml_dir: "{{ working_yamls_dir }}/{{ name }}"

- debug:
    msg: "yamls will be written to {{ __yaml_dir }} locally"

- name: Create yaml dir
  file:
    path: "{{ __yaml_dir }}"
    state: directory
    mode: 0755
