---
- name: Set cinder nfs directories
  set_fact:
    nfs_cinder_dir: "{{ nfs_export_dir }}/cinder"
    nfs_cinder_backup_dir: "{{ nfs_export_dir }}/cinder-backup"

- name: Create cinder nfs directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    group: nobody
    owner: nobody
  with_items:
    - "{{ nfs_cinder_dir }}"
    - "{{ nfs_cinder_backup_dir }}"

- name: Configure cinder export
  lineinfile:
    create: true
    path: /etc/exports.d/cinder.exports
    line: "{{ item }} *(rw,sync,no_root_squash)"
    mode: '0644'
  with_items:
    - "{{ nfs_cinder_dir }}"
    - "{{ nfs_cinder_backup_dir }}"

- name: Export NFS share to the server
  command: "exportfs -r"
