---
#
# Cinder
#
- name: Set directory for cinder yaml files
  ansible.builtin.set_fact:
    cinder_yaml_dir: "{{ working_yamls_dir }}/cinder"

- name: Show yaml output dir
  ansible.builtin.debug:
    msg: "yamls will be written to {{ cinder_yaml_dir }} locally"

- name: Clean yaml dir
  ansible.builtin.file:
    state: absent
    path: "{{ cinder_yaml_dir }}/"

- name: Create yaml dir
  ansible.builtin.file:
    path: "{{ cinder_yaml_dir }}"
    state: directory
    mode: "0755"

- name: Copy files to yaml dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ cinder_yaml_dir }}/"
    mode: "0644"
  with_fileglob:
    - "cinder/*"

- name: Create Cinder custom ConfigMaps
  ansible.builtin.shell: |
    set -e
    oc apply -n openstack -f "{{ cinder_yaml_dir }}"
  environment:
    PATH: "{{ oc_env_path }}"
    KUBECONFIG: "{{ kubeconfig }}"
