---
- name: create openstackclient yamls dir
  file:
    path: "{{ working_dir }}/yamls/openstackclient"
    state: directory
    mode: '0755'

- name: create openstackclient-pod.yaml from template
  vars:
    os_password: foobar123
    os_auth_url: http://keystone-openstack.apps.ostest.test.metalkube.org/
  template:
    src:  "openstackclient-pod.yaml.j2"
    dest: "{{ working_dir }}/yamls/openstackclient/openstackclient-pod.yaml"
    mode: '0644'

- name: Delete openstackclient pod
  shell: |
    oc delete --ignore-not-found -n openstack -f {{ working_dir }}/yamls/openstackclient/openstackclient-pod.yaml
  environment:
    PATH: "{{ oc_env_path }}"
    KUBECONFIG: "{{ kubeconfig }}"
