---
- name: Set directory for ovn yaml files
  set_fact:
    ovn_yaml_dir: "{{ working_yamls_dir }}/ovn"

- name: show yaml output dir
  debug:
    msg: "yamls will be written to {{ ovn_yaml_dir }} locally"

- name: Clean yaml dir
  file:
    state: absent
    path: "{{ ovn_yaml_dir }}/"

- name: Create yaml dir
  file:
    path: "{{ ovn_yaml_dir }}"
    state: directory
    mode: '0755'

- name: Copy deployment yamls to working dir
  copy:
    src: "{{ item }}"
    dest: "{{ ovn_yaml_dir }}/"
    mode: '0644'
  with_fileglob:
  - "ovn/*"

- name: Delete OVN
  shell: |
    oc delete --ignore-not-found -f "{{ ovn_yaml_dir }}"
  environment: &oc_env
    PATH: "{{ oc_env_path }}"
    KUBECONFIG: "{{ kubeconfig }}"

- name: Delete ovn-connection config map
  shell: |
    oc delete --ignore-not-found configmap -n openstack ovn-connection
  environment:
    <<: *oc_env
