---
- name: Check if rhos-release exists
  ansible.builtin.stat:
    path: "{{ rhos_release_bin }}"
  register: rhos_release_command_stat

- name: Define rhos_release_command fact
  ansible.builtin.set_fact:
    rhos_release_command: "{{ rhos_release_bin }}"
  when: rhos_release_command_stat.stat.exists
