---
- name: Install rhos-release package
  become: true
  retries: 3
  delay: 5
  ansible.builtin.package:
    name: "{{ rhos_release_rpm_url }}"
  register: task_result
  until: task_result is success
