---
- name: Install NFS packages
  ansible.builtin.dnf:
    name: nfs-utils
    state: present

- name: Start and enable NFS services
  ansible.builtin.systemd:
    name: nfs-server
    state: started
    enabled: true

- name: Open nfsv4 port 2049/tcp (permanent config)
  ansible.posix.firewalld:
    zone: libvirt
    port: 2049/tcp
    permanent: true
    state: enabled

- name: Open nfsv4 port 2049/tcp (running config)
  ansible.posix.firewalld:
    zone: libvirt
    port: 2049/tcp
    state: enabled
