- name: Install NFS packages
  yum:
    name: nfs-utils
    state: present

- name: Start and enable NFS services
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: open nfsv4 port 2049/tcp (permanent config)
  firewalld:
    zone: libvirt
    port: 2049/tcp
    permanent: yes
    state: enabled

- name: open nfsv4 port 2049/tcp (running config)
  firewalld:
    zone: libvirt
    port: 2049/tcp
    state: enabled
