#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files: "vars/default.yaml"
  roles:
  - oc_local

  tasks:
  - name: Deinstall cnosp operators
    include_role:
      name: cnosp
      tasks_from: olm_cleanup
    vars:
      _csv_version: "{{ cnosp_csv_version }}"
