#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files: "vars/default.yaml"
  roles:
  - oc_local

  tasks:
  - name: Set combined osp dict
    set_fact:
      osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

  - name: Set path to RHEL base image for dev-scripts
    set_fact:
      osp_controller_base_image_url_path: "{{ base_path }}/ironic/html/images/{{ osp.controller.base_image_url | basename }}"
    when: not (ocp_ai|bool)

  - name: Set path to RHEL base image for assisted installer
    set_fact:
      osp_controller_base_image_url_path: "/opt/http_store/data/images/{{ osp.controller.base_image_url | basename }}"
    when: ocp_ai|bool

  # NOTE: we copy this to the Ironic images directory to reuse it for
  # the provision server (openstackbaremetalsets). This avoids downloading
  # the same image twice.
  - name: Check if {{ osp.controller.base_image_url | basename }} already exist
    stat:
      path: "{{ osp_controller_base_image_url_path }}"
    register: stat_result

  # Note: the CentOS image right now has some ifcfg configs, lets make sure they are deleted
  - name: Get RHEL/CentOS guest base image
    become: true
    become_user: ocp
    when: not stat_result.stat.exists
    block:
      - name: Download RHEL/CentOS guest image {{ osp.controller.base_image_url }}
        get_url:
          url: "{{ osp.controller.base_image_url }}"
          dest: "{{ osp_controller_base_image_url_path }}"
          owner: ocp
          group: ocp
          mode: '0644'
          timeout: 30

      - name: Remove net.ifnames=0 kernel param from {{ osp_controller_base_image_url_path }}
        shell: |
          #!/bin/bash
          set -e
          virt-customize -a "{{ osp_controller_base_image_url_path }}" \
            --run-command 'sed -i -e "s/^\(GRUB_CMDLINE_LINUX=.*\)net.ifnames=0 \(.*\)/\1\2/" /etc/default/grub' \
            --run-command 'grub2-mkconfig -o /etc/grub2.cfg' \
            --run-command 'rm -f /etc/sysconfig/network-scripts/ifcfg-ens* /etc/sysconfig/network-scripts/ifcfg-eth*'

  # Make sure we delete the datavolume e.g. when switch from rhel image to centos image
  # This won't solve the problem when the both images exist and we switch back.
  - name: delete datavolume if image got downloaded
    when: not stat_result.stat.exists
    shell: >
      oc delete datavolume --ignore-not-found=true openstack-base-img -n {{ namespace }}
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: does the datavolume already exist
    ignore_errors: true
    shell: >
      oc get datavolume openstack-base-img -n {{ namespace }}
    environment:
      <<: *oc_env
    register: datavolume_switch

  - name: Deploy the datavolume
    when: datavolume_switch.rc == 1
    environment:
      <<: *oc_env
    block:
      - name: Upload OSP Controller base image
        shell: |
          virtctl image-upload dv openstack-base-img -n {{ namespace }} --size={{ osp.controller.disk_size }}G --image-path={{ osp_controller_base_image_url_path }} --insecure
    rescue:
      - name: Remove datavolume from failed OSP Controller upload
        command: oc delete datavolume openstack-base-img -n {{ namespace }}
        ignore_errors: yes

      - name: Re-Upload OSP Controller base image
        shell: |
          virtctl image-upload dv openstack-base-img -n {{ namespace }} --size={{ osp.controller.disk_size }}G --image-path={{ osp_controller_base_image_url_path }} --insecure

  - name: Wait for the datavolume to be ready
    retries: 5
    delay: 5
    shell: |
      oc wait datavolume openstack-base-img --for condition=Ready -n "{{ namespace }}" --timeout={{ default_timeout }}s
    environment:
      <<: *oc_env
