---
- name: Demo
  hosts: localhost
  vars_files: "vars/default.yaml"
  roles:
    - oc_local

  tasks:
    - name: Create demo directory
      ansible.builtin.file:
        path: "{{ working_dir }}/demo"
        state: directory
        mode: "0755"

    - name: Copy demo files to {{ working_dir }}/demo
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ working_dir }}/demo/"
        mode: "0644"
      with_fileglob:
        - files/demo/*

    - name: Create htpasswd file
      ansible.builtin.lineinfile:
        path: "{{ working_dir }}/demo/htpasswd"
        line: "demo:$apr1$SeAzqzN/$UPXamQYHPy/mlyIxoyQ9b0" # password is demo
        state: present
        create: true
        mode: "0644"

    - name: Create secret for htpasswd file
      ansible.builtin.shell: |
        if oc get secret htpass-secret -n openshift-config; then
          oc delete secret htpass-secret -n openshift-config
        fi
        oc create secret generic htpass-secret --from-file=htpasswd={{ working_dir }}/demo/htpasswd -n openshift-config
      environment: &oc_env
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Create htpasswd identity provider
      ansible.builtin.shell: |
        oc apply -f {{ working_dir }}/demo/htpasswd-identity-provider.yaml
      environment:
        <<: *oc_env

    - name: Create clusterrolebinding for cluster-admin to demo user
      ansible.builtin.shell: |
        if ! oc get clusterrolebinding demo-crb; then
          oc create clusterrolebinding demo-crb --clusterrole cluster-admin --user demo
        fi
      environment:
        <<: *oc_env

    - name: Delete OLM subscription
      ansible.builtin.shell: |
        oc delete --ignore-not-found -n openstack subscription osp-director-operator
      environment:
        <<: *oc_env

    - name: Delete OLM operator group
      ansible.builtin.shell: |
        oc delete --ignore-not-found -n openstack operatorgroup osp-director-operator
      environment:
        <<: *oc_env

    - name: Delete OLM csv
      ansible.builtin.shell: |
        oc delete --ignore-not-found -n openstack csv osp-director-operator.v{{ csv_version }}
      environment:
        <<: *oc_env
