---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set directory for networks yaml files
    set_fact:
      network_yaml_dir: "{{ working_yamls_dir }}/networks"

  - debug:
      msg: "yamls will be written to {{ network_yaml_dir }} locally"

  - name: Clean yaml dir
    file:
      state: absent
      path: "{{ network_yaml_dir }}/"

  - name: Create yaml dir
    file:
      path: "{{ network_yaml_dir }}"
      state: directory
      mode: '0755'

  - name: Render templates to yaml dir
    template:
      src: "osp/networks/{{ item }}.j2"
      dest: "{{ network_yaml_dir }}/{{ item }}"
      mode: '0644'
    with_items:
    - "01-ctlplane.yaml"

  - name: do the networks already exist
    ignore_errors: true
    shell: >
      oc get openstacknet ctlplane
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: openstack_net_switch

  - name: Start networks
    shell: |
      set -e
      oc apply -n openstack -f "{{ network_yaml_dir }}"
    environment:
      <<: *oc_env
    when: openstack_net_switch.rc == 1
