---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set directory for compute yaml files
    set_fact:
      ctlplane_yaml_dir: "{{ working_yamls_dir }}/ctlplane"

  - debug:
      msg: "yamls will be written to {{ ctlplane_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ ctlplane_yaml_dir }}"
      state: directory
      mode: '0755'

  - name: Render templates to yaml dir
    template:
      src: "osp/ctlplane/{{ item }}.j2"
      dest: "{{ ctlplane_yaml_dir }}/{{ item }}"
      mode: '0644'
    with_items:
    - "osp-director_controlplane.yaml"
    - "password-secret.yaml"

  - name: Start ctlplane
    shell: |
      set -e
      oc apply -n openstack -f "{{ ctlplane_yaml_dir }}"
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
