---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      ns_yaml_dir: "{{ working_yamls_dir }}/namespace"

  - name: Create namespace yaml dir
    file:
      path: "{{ ns_yaml_dir }}"
      state: directory

  - name: Copy common namespace to working dir
    copy:
      src: "{{ item }}"
      dest: "{{ ns_yaml_dir }}/"
    with_fileglob:
    - "ocp/namespace/*"

  - name: Deploy namespace
    shell: |
      oc apply -f "{{ ns_yaml_dir }}/namespace.yaml"
      oc apply -f "{{ ns_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
