---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set combined osp dict
    set_fact:
      osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

  - name: Set directory for compute yaml files
    set_fact:
      ctlplane_yaml_dir: "{{ working_yamls_dir }}/ctlplane"

  - debug:
      msg: "yamls will be written to {{ ctlplane_yaml_dir }} locally"

  - name: Clean yaml dir
    file:
      state: absent
      path: "{{ ctlplane_yaml_dir }}/"

  - name: Create yaml dir
    file:
      path: "{{ ctlplane_yaml_dir }}"
      state: directory
      mode: '0755'

  - name: Render templates to yaml dir
    template:
      src: "osp/ctlplane/{{ item }}.j2"
      dest: "{{ ctlplane_yaml_dir }}/{{ item }}"
      mode: '0644'
    with_items:
    - "osp-director_openstackcontrolplane.yaml"
    - "password-secret.yaml"
    - "idm-secret.yaml"

  - name: Start ctlplane
    shell: |
      set -e
      oc apply -n {{ namespace }} -f "{{ ctlplane_yaml_dir }}"
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
