---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set directory for namespace yaml files
    set_fact:
      ns_yaml_dir: "{{ working_yamls_dir }}/namespace"

  - name: Create namespace yaml dir
    file:
      path: "{{ ns_yaml_dir }}"
      state: directory

  - name: Render common namespace template to working dir
    template:
      src: "namespace/{{ item }}.j2"
      dest: "{{ ns_yaml_dir }}/{{ item }}"
    with_items:
    - "namespace.yaml"

  - name: Deploy namespace
    shell: |
      oc apply -f "{{ ns_yaml_dir }}/namespace.yaml"
      oc apply -f "{{ ns_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
