---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set directory for compute yaml files
    set_fact:
      compute_yaml_dir: "{{ working_yamls_dir }}/compute"

  - debug:
      msg: "yamls will be written to {{ compute_yaml_dir }} locally"

  - name: Clean yaml dir
    file:
      state: absent
      path: "{{ compute_yaml_dir }}/"

  - name: Create yaml dir
    file:
      path: "{{ compute_yaml_dir }}"
      state: directory
      mode: '0755'

  - name: Detach additional Ceph OSD disks
    shell: |
      #!/bin/bash
      for domain in $(virsh list --inactive --name); do
        for disk in $(virsh domblklist ${domain} | grep ceph | awk '{print $1}'); do
          virsh detach-disk  ${domain} ${disk} --persistent
          rm -f /home/ocp/pool/${domain}-ceph-disk-${disk}.qcow2
        done
      done
    become: true
    become_user: root

  - name: Create additional Ceph OSD disks
    shell: |
      #!/bin/bash
      for domain in $(virsh list --inactive --name); do
        qemu-img create -f qcow2 -o preallocation=falloc /home/ocp/pool/${domain}-ceph-disk-{{ item }}.qcow2 {{ osp_compute_ceph_num_osd_disk_size }}G
        virsh attach-disk ${domain} --source /home/ocp/pool/${domain}-ceph-disk-{{ item }}.qcow2 --target {{ item }} --persistent
      done
    with_items: "{{ osp_compute_ceph_osd_disks }}"
    become: true
    become_user: root

  - name: register dev-tools prepared extra_hosts
    shell: |
      set -e
      oc apply -f {{ base_path }}/dev-scripts/ocp/ostest/extra_host_manifests.yaml
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Render templates to yaml dir
    template:
      src: "osp/compute/{{ item }}.j2"
      dest: "{{ compute_yaml_dir }}/{{ item }}"
      mode: '0644'
    with_items:
    - "openstackprovisionserver.yaml"
    - "openstackbaremetalset.yaml"

  - name: does the provisionserver already exist
    shell: >
      oc get -n openstack osprovserver openstack -o json --ignore-not-found
    environment:
      <<: *oc_env
    register: provisionserver_switch

  - name: Start provisionserver
    shell: |
      set -e
      oc apply -n openstack -f "{{ compute_yaml_dir }}/openstackprovisionserver.yaml"
    environment:
      <<: *oc_env
    when: provisionserver_switch.stdout | length == 0

  - name: Start baremetalset
    shell: |
      set -e
      oc apply -n openstack -f "{{ compute_yaml_dir }}/openstackbaremetalset.yaml"
    environment:
      <<: *oc_env
