---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Set directory for networks yaml files
    set_fact:
      network_yaml_dir: "{{ working_yamls_dir }}/networks"

  - debug:
      msg: "yamls will be written to {{ network_yaml_dir }} locally"

  - name: Clean yaml dir
    file:
      state: absent
      path: "{{ network_yaml_dir }}/"

  - name: Create yaml dir
    file:
      path: "{{ network_yaml_dir }}"
      state: directory
      mode: '0755'

  - name: Render templates to yaml dir
    template:
      src: "osp/networks/{{ item }}.j2"
      dest: "{{ network_yaml_dir }}/{{ item }}"
      mode: '0644'
    with_items:
    - "01-ctlplane.yaml"
    - "02-internalapi.yaml"
    - "03-external.yaml"
    - "04-tenant.yaml"
    - "05-storage.yaml"
    - "06-storagemgmt.yaml"

  - name: does the networks already exist
    shell: >
      oc get osnet -n openstack ctlplane internalapi --ignore-not-found
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: network_exist_switch
    # Retry on failure, probably osnet does not exist yet
    retries: 15
    delay: 10
    until: network_exist_switch.rc == 0

  - name: Start networks
    shell: |
      set -e
      oc apply -n openstack -f "{{ network_yaml_dir }}"
    environment:
      <<: *oc_env
    when: network_exist_switch.stdout | length == 0
