---
# https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.2/html/advanced_overcloud_customization/sect-enabling_ssltls_on_the_overcloud
- name: Create local CA
  become: true
  become_user: root
  block:
    - name: Create local CA directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - /opt/local_CA
        - /opt/local_CA/private
        - /opt/local_CA/certs
        - /opt/local_CA/newcerts
        - /opt/local_CA/crl
        - /opt/local_CA/certs/openstack

    - name: Create pki CA index
      ansible.builtin.file:
        path: /opt/local_CA/index.txt
        state: touch
        mode: "0644"
        modification_time: preserve
        access_time: preserve

    - name: Create pki CA serial
      ansible.builtin.copy:
        dest: /opt/local_CA/serial
        content: |
          1000
        force: false
        mode: "0644"

    - name: Create local CA
      ansible.builtin.command:
        cmd: openssl req -x509 -nodes -newkey rsa:4096 -keyout /opt/local_CA/private/cakey.pem -out /opt/local_CA/cacert.pem -days 7300 -extensions v3_ca -subj
          '/C=US/ST=North Carolina/L=Raleigh/O=Red Hat/OU=OSP Director Operator devtools/CN={{ ansible_fqdn }}' -batch
        creates: /opt/local_CA/cacert.pem
