---
- hosts: localhost
  vars_files: vars/default.yaml
  become: true
  become_user: root
  roles:
  - oc_local

  tasks:
  - name: Include Local Storage Operator tasks
    include_tasks: local_storage_tasks.yaml
