---
- name: Must-Gather
  hosts: localhost
  vars_files: vars/default.yaml
  roles:
    - oc_local

  tasks:
    - name: Include variables
      ansible.builtin.include_vars: vars/default.yaml
    - name: Must-gather run dir
      ansible.builtin.set_fact:
        _must_gather_dir: "{{ must_gather_directory | default(working_log_dir) }}/must-gather-{{ ansible_date_time.iso8601_basic }}"

    - name: Create must-gather run dir
      ansible.builtin.file:
        path: "{{ _must_gather_dir }}"
        state: directory
        mode: "0755"

    - name: Run must-gather
      ansible.builtin.shell: |
        #!/bin/bash
        set -e
        oc adm must-gather \
          --image={{ must_gather_image }} \
          --dest-dir={{ _must_gather_dir }}
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Zip must-gather
      community.general.archive:
        path: "{{ _must_gather_dir }}"
        dest: "{{ _must_gather_dir }}.zip"
        format: zip
        remove: true
        mode: "0644"
      when: must_gather_compress_logs | default(false) | bool
