---
- name: OpenShift User
  hosts: convergence_base
  gather_facts: false
  become: true

  tasks:
    - name: Create ocp group
      ansible.builtin.group:
        name: ocp
        state: present

    - name: Create user to run installer dev scripts
      ansible.builtin.user:
        name: ocp
        comment: ocp user
        shell: /bin/bash
        group: ocp
        groups: wheel

    - name: Make sure /home/ocp is world readable
      ansible.builtin.file:
        path: /home/ocp
        state: directory
        mode: "0755"
