---
- name: Destroy the dev-scripts OCP cluster
  import_playbook: ocp_dev_scripts_destroy.yaml

- name: Destroy the assisted installer OCP cluster
  import_playbook: ocp_ai_destroy.yaml

- name: Cleanup libvirt resources
  import_playbook: libvirt_cleanup.yaml
