---
- hosts: convergence_base
  become: true
  gather_facts: false

  tasks:
  - name: Include default variables
    include_vars: vars/default.yaml

  - name: Include AI variables
    include_vars: vars/ocp_ai.yaml


### EXECUTE ASSISTED INSTALLER PLAYBOOK

  - name: Delete existing AI cluster (if any)
    command: "aicli -U http://{{ ocp_ai_bm_ip }}:{{ ocp_ai_service_port | default('8090', true) }} delete cluster {{ ocp_cluster_name }}"

  - name: Run the assisted installer playbook
    shell: ansible-playbook -i inventory.ospd deploy_cluster.yml
    args:
      chdir: "{{ base_path }}/cluster_mgnt_roles"