---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: check if osp network already exists
    become: true
    become_user: root
    shell: >
      virsh net-info ospnetwork
    ignore_errors: true
    register: ospnetwork_exist

  - name: check if osp external network already exists
    become: true
    become_user: root
    shell: >
      virsh net-info external
    ignore_errors: true
    register: extnetwork_exist

  - name: create osp networks
    when: ospnetwork_exist.rc == 1 or extnetwork_exist.rc == 1
    block:
    - name: create osp network directory
      file:
        path: "{{ working_dir }}/osp-network"
        state: directory
        mode: '0755'

    - name: copy osp network files to {{ working_dir }}/osp-network
      copy:
        src:  "{{ item }}"
        dest: "{{ working_dir }}/osp-network/"
        mode: 0644
      with_items:
        - files/ospnetwork.xml
        - files/externalnetwork.xml

    - name: Define ospnetwork libvirt network
      become: true
      become_user: root
      command: "virsh net-define {{ working_dir }}/osp-network/ospnetwork.xml"
      when: ospnetwork_exist.rc == 1

    - name: Define external libvirt network
      become: true
      become_user: root
      command: "virsh net-define {{ working_dir }}/osp-network/externalnetwork.xml"
      when: extnetwork_exist.rc == 1

  - name: Setup OSP network
    become: true
    become_user: root
    block:
    - name: Start the osp networks
      shell: |
        virsh net-start --network {{ item }}
        virsh net-autostart --network {{ item }}
      register: network_start
      failed_when: network_start.stderr != "" and "network is already active" not in network_start.stderr
      with_items:
        - external
        - ospnetwork

    - name: get active worker nodes, if they exist
      shell: >
          echo $(virsh list --name | grep worker)
      register: worker_ocp_active_dedicated
      when: ocp_num_workers > 0

    - name: get active master nodes and count them as workers, if this cluster has no dedicated workers
      shell: >
          echo $(virsh list --name | grep master)
      register: worker_ocp_active_masters
      when: ocp_num_workers < 1

    - name: set active worker nodes fact, if dedicated workers exist
      set_fact:
        worker_ocp_active: "{{ worker_ocp_active_dedicated.stdout_lines }}"
      when: "'stdout_lines' in worker_ocp_active_dedicated and worker_ocp_active_dedicated.stdout_lines|length > 0"

    - name: set active worker nodes fact, if no dedicated workers exist
      set_fact:
        worker_ocp_active: "{{ worker_ocp_active_masters.stdout_lines }}"
      when: "'stdout_lines' in worker_ocp_active_masters and worker_ocp_active_masters.stdout_lines|length > 0"

    - name: get inactive worker nodes
      shell: >
          echo $(virsh list --inactive --name | grep worker)
      register: worker_ocp_inactive

    - name: Attach/detach network interfaces for INACTIVE workers
      when: worker_ocp_inactive.stdout_lines|length > 0
      block:
      - name: Detach network interface from INACTIVE worker VM's if this is a rerun of the playbook
        shell: |
          ifmacs=$(virsh domiflist {{ item.0 }} | grep {{ item.1 }} | awk '{ print $5}')
          for mac in $ifmacs; do
            virsh detach-interface {{ item.0 }} bridge --mac $mac --persistent
          done
        with_nested:
        - "{{ worker_ocp_inactive.stdout_lines[0].split(' ') }}"
        - ['external', 'ospnetwork']
        ignore_errors: true

      - name: Attach the osp network to INACTIVE worker VM's
        command: "virsh attach-interface {{ item.0 }} bridge {{ item.1 }} --model virtio --persistent"
        with_nested:
        - "{{ worker_ocp_inactive.stdout_lines[0].split(' ') }}"
        - ['external', 'ospnetwork']

    - name: Attach/detach network interfaces for ACTIVE workers
      when: worker_ocp_active|length > 0
      block:
      - name: Detach osp network interface from ACTIVE worker VM's if this is a rerun of the playbook
        shell: |
          ifmacs=$(virsh domiflist {{ item.0 }} | grep {{ item.1 }} | awk '{ print $5}')
          for mac in $ifmacs; do
            virsh detach-interface {{ item.0 }} bridge --mac $mac --persistent --live
          done
        with_nested:
        - "{{ worker_ocp_active[0].split(' ') }}"
        - ['external',  'ospnetwork']
        ignore_errors: true

      - name: Attach the osp network to ACTIVE worker VM's
        when: not (ocp_ai|bool)
        block:
        # HACK to fix dev-scripts bug
        - name: "destroy vm {{ item }}"
          command: "virsh destroy {{ item }}"
          with_items: "{{ worker_ocp_active[0].split(' ') }}"
        - name: attach interfaces to vm
          shell: |
            virsh attach-interface {{ item.0 }} bridge {{ item.1 }} --model virtio --persistent --config
          with_nested:
          - "{{ worker_ocp_active[0].split(' ') }}"
          - ['external', 'ospnetwork']
        - name: "start vm {{ item }}"
          command: "virsh start {{ item }}"
          with_items: "{{ worker_ocp_active[0].split(' ') }}"

      - name: Attach the osp network to ACTIVE worker VM's
        command: "virsh attach-interface {{ item.0 }} bridge {{ item.1 }} --model virtio --persistent --config"
        with_nested:
        - "{{ worker_ocp_active[0].split(' ') }}"
        - ['external', 'ospnetwork']
        when: ocp_ai|bool
