---
- name: Update OpenShift pull secret with additional registry credentials
  hosts: localhost
  vars_files: vars/default.yaml
  roles:
    - oc_local

  tasks:
    - name: Load registry credentials from secrets_repo
      when: secrets_repo is defined
      block:
        - name: Set secrets_repo_path
          ansible.builtin.set_fact:
            secrets_repo_path: "{{ ansible_env.HOME }}/{{ secrets_repo | urlsplit('hostname') }}/{{ (secrets_repo | urlsplit('path') | splitext)[0] }}"

        - name: Create base dir for secrets_repo
          ansible.builtin.file:
            path: "{{ secrets_repo_path }}"
            state: directory
            mode: "0755"

        - name: Clone the repo specified in secrets_repo
          ansible.builtin.git:
            repo: "{{ secrets_repo }}"
            dest: "{{ secrets_repo_path }}"
            version: "{{ secrets_branch | default('HEAD', true) }}"
          environment:
            GIT_SSL_NO_VERIFY: "true"

        - name: Check if registry credentials file exists in secrets_repo
          ansible.builtin.stat:
            path: "{{ secrets_repo_path }}/registry-credentials.yaml"
          register: secrets_repo_registry_creds

        - name: Include registry credentials from secrets_repo
          ansible.builtin.include_vars: "{{ secrets_repo_path }}/registry-credentials.yaml"
          when: secrets_repo_registry_creds.stat.exists

    - name: Display message if no credentials found
      ansible.builtin.debug:
        msg: "No registry-credentials.yaml found in secrets_repo or secrets_repo not defined, skipping pull secret and ICSP updates"
      when: registry_credentials is not defined or registry_credentials | length == 0

    - name: Update pull secret with registry credentials
      when: registry_credentials is defined and registry_credentials | length > 0
      block:
        - name: Set temporary authfile path
          ansible.builtin.set_fact:
            authfile_path: "{{ working_yamls_dir }}/authfile"

        - name: Ensure working directory exists
          ansible.builtin.file:
            path: "{{ working_yamls_dir }}"
            state: directory
            mode: "0755"

        - name: Get current pull secret from OpenShift
          ansible.builtin.shell: |
            oc get secret/pull-secret -n openshift-config -o json | jq -r '.data.".dockerconfigjson"' | base64 -d > {{ authfile_path }}
          environment: &oc_env
            PATH: "{{ oc_env_path }}"
            KUBECONFIG: "{{ kubeconfig }}"

        - name: Add registry credentials to authfile using podman login
          ansible.builtin.shell: |
            podman login --authfile {{ authfile_path }} --username "{{ item.username }}" --password "{{ item.password }}" {{ item.registry }}
          loop: "{{ registry_credentials }}"
          no_log: true

        - name: Update pull secret in OpenShift
          ansible.builtin.shell: |
            oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson={{ authfile_path }}
          environment:
            <<: *oc_env

        - name: Create ImageContentSourcePolicy YAML files for registry mirrors
          ansible.builtin.template:
            src: templates/redhat-registry-mirror-icsp.yaml.j2
            dest: "{{ working_yamls_dir }}/{{ item.registry | replace('.', '-') }}-ImageContentSourcePolicy.yaml"
            mode: "0644"
          loop: "{{ registry_credentials }}"

        - name: Apply ImageContentSourcePolicy to OpenShift
          ansible.builtin.shell: |
            oc apply -f {{ working_yamls_dir }}/{{ item.registry | replace('.', '-') }}-ImageContentSourcePolicy.yaml
          environment:
            <<: *oc_env
          loop: "{{ registry_credentials }}"

        - name: Wait for MachineConfigPool to update after ICSP changes
          ansible.builtin.shell: |
            oc wait mcp/worker --for condition=Updated --timeout=600s || true
            oc wait mcp/master --for condition=Updated --timeout=600s || true
          environment:
            <<: *oc_env
          ignore_errors: true

        - name: Wait for cluster to stabilize after pull secret and ICSP updates
          ansible.builtin.shell: |
            oc adm wait-for-stable-cluster --minimum-stable-period=1m --timeout={{ (default_timeout * 10) | int }}s
          environment:
            <<: *oc_env
          ignore_errors: true

      always:
        - name: Remove temporary authfile
          ansible.builtin.file:
            path: "{{ authfile_path }}"
            state: absent
          when: authfile_path is defined
