---
- hosts: convergence_base
  become: true
  become_user: root
  gather_facts: false

  tasks:
  - name: Include default variables
    include_vars: vars/default.yaml

  - name: Include AI variables
    include_vars: vars/ocp_ai.yaml

  - name: Set combined osp dict
    set_fact:
      osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"


  ### DNSMASQ

  - name: Remove dnsmasq conf
    file:
      path: "/etc/dnsmasq.d/dnsmasq_ai.conf"
      state: absent

  - name: Remove dnsmasq DNS conf
    file:
      path: "/etc/NetworkManager/conf.d/dnsmasq.conf"
      state: absent

  - name: Remove dnsmasq leases
    file:
      path: "/var/lib/dnsmasq/dnsmasq.leases"
      state: absent

  - name: Restart NetworkManager
    service:
      name: NetworkManager
      state: restarted
      enabled: yes

  - name: Stop dnsmasq
    service:
      name: dnsmasq
      state: stopped


  ### VMs

  - name: Delete VMs and disk QCOW2s
    shell: |
      for i in $(virsh list | grep "{{ ocp_cluster_name }}-" | awk '{print $2}'); do
        virsh destroy $i
      done

      for i in $(virsh list --all | grep "{{ ocp_cluster_name }}-" | awk '{print $2}'); do
        virsh undefine --nvram $i
        rm -f $(virsh pool-dumpxml default|grep -o "<path>.*</path>"|sed 's/\(<path>\|<\/path>\)//g')/$i.qcow2
      done


  ### SUSHY-TOOLS

  - name: Stop sushy-tools service
    service:
      name: sushy-tools
      state: stopped
      enabled: no
    ignore_errors: true

  - name: Delete sushy-tools service
    file:
      path: /etc/systemd/system/sushy-tools.service
      state: absent

  - name: Reload systemd service
    systemd:
      daemon_reload: yes


  ### HTTP STORE

  - name: Stop and remove httpd container
    containers.podman.podman_container:
      name: httpd
      image: quay.io/openstack-k8s-operators/httpd-24-centos7:2.4
      state: absent


  ### ASSISTED INSTALLER SERVICE CONTAINERS

  - name: Stop and remove assisted installer service containers
    shell: |
      podman pod stop assisted-installer;
      podman pod rm assisted-installer -f
    ignore_errors: true

  - name: Remove Postgres data store
    file:
      path: "{{ ocp_ai_service_store_dir | default('/opt/assisted-installer', true) }}/data/postgresql"
      state: absent


  ### BRIDGES

  - name: Delete BM interface to BM bridge if defined
    nmcli:
      conn_name: "bridge-slave-{{ ocp_bm_interface }}"
      type: bridge-slave
      ifname: "{{ ocp_bm_interface }}"
      master: "{{ ocp_cluster_name }}bm"
      state: absent
    when: ocp_bm_interface is defined and ocp_bm_interface != ""

  - name: Delete AI bridges
    block:
    - name: Delete existing bridges (if any)
      nmcli:
        conn_name: "{{ ocp_cluster_name }}{{ item }}"
        type: bridge
        state: absent
      with_items:
        - bm
        - pr

    - name: Make sure bridge ifcfg files are removed
      file:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{ ocp_cluster_name }}{{ item }}"
        state: absent
      with_items:
        - bm
        - pr
    ignore_errors: true

  - name: Delete osp network bridge
    nmcli:
      conn_name: ospnetwork
      type: bridge
      state: absent

  - name: Make sure osp network ifcfg files are removed
    file:
      path: /etc/sysconfig/network-scripts/ifcfg-ospnetwork
      state: absent

  - name: Delete osp network bridge slave (if any)
    nmcli:
      conn_name: "bridge-slave-{{ osp_bm_interface }}"
      type: bridge-slave
      state: absent
    when: osp_bm_interface|default("") != ""

  - name: Make sure osp network bridge slave is removed (if any)
    file:
      path: "/etc/sysconfig/network-scripts/ifcfg-bridge-slave-{{ osp_bm_interface }}"
      state: absent
    when: osp_bm_interface|default("") != ""

  ### remove osp_base_image

  - name: Set path to RHEL base image for assisted installer
    set_fact:
      osp_base_image_url_path: "/opt/http_store/data/images/{{ osp.base_image_url | basename }}"

  - name: Delete {{ osp_base_image_url_path }}
    file:
      path: "{{ osp_base_image_url_path }}"
      state: absent

  - name: Find discovery images
    find:
      paths: "/var/lib/libvirt/images/"
      patterns: "discovery_image_{{ ocp_cluster_name }}*.img"
    register: discovery_images

  - name: Delete discovery images
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - "{{ discovery_images.files }}"

  - name: Delete AI podman images
    shell: |
      for i in $(podman images | grep -E '(assisted-service|ocp-metal-ui)' | awk '{print $3}'); do podman rmi $i; done

  - name: Cleanup crucible
    become: true
    block:
    - name: Cleanup crucible repo
      file:
        path: "{{ base_path }}/crucible"
        state: absent

    - name: Cleanup ansible
      file:
        path: "{{ base_path }}/.ansible"
        state: absent
