---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: olm cleanup
    command: "{{ item }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    ignore_errors: true
    with_items:
      - "oc delete -n {{ namespace }} csv osp-director-operator.v{{ csv_version }}"
      - "oc delete -n {{ namespace }} subscription osp-director-operator-subscription"
      - "oc delete -n {{ namespace }} catalogsource osp-director-operator-index"
      - "oc delete -n {{ namespace }} operatorgroup osp-director-operator-group"
