---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:

  #NOTE: operatorgroup is named differently depending if it is created via
  # the webUI so we register the name here and delete it below by name
  - name: set operatorgroup name
    ignore_errors: true
    shell: >
      oc get operatorgroup -n {{ namespace }} -o name
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: operatorgroup_name


  - name: olm cleanup
    command: "{{ item }}"
    environment:
      <<: *oc_env
    ignore_errors: true
    with_items:
      - "oc delete -n {{ namespace }} csv osp-director-operator.v{{ csv_version }}"
      - "oc delete -n {{ namespace }} subscription osp-director-operator"
      - "oc delete -n {{ namespace }} catalogsource osp-director-operator-index"
      - "oc delete -n {{ namespace }} {{ operatorgroup_name.stdout }}"

