---
- name: Configure multi-rhel computes upgrade
  hosts: localhost
  vars_files: vars/default.yaml
  roles:
    - oc_local

  tasks:
    - name: Set combined osp dict
      ansible.builtin.set_fact:
        osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

    - name: Set role facts
      ansible.builtin.set_fact:
        compute_roles: "{{ osp.bmset | dict2items | selectattr('value.count', '>', 1) | list | items2dict | list }}"

# Computes to RHEL9

# Multi-rhel remaining computes
- name: Compute system upgrade config generate
  import_playbook: config_generator.yaml
  vars:
    custom_config_name: system-upgrade
    config_generator_name: system-upgrade-computes
    config_generator_action: system-upgrade-computes
  when: compute_roles | length > 0

- name: System upgrade remaining Computes
  import_playbook: osp_deployment.yaml
  vars:
    config_generator_name: system-upgrade-computes
    deploy_name: system-upgrade-computes
    deploy_mode: upgrade
    deploy_advanced_settings:
      # e.g limit: "!Compute[0],!ComputeHCI[0],Compute,ComputeHCI"
      limit: "{{ (compute_roles | map('regex_replace', '^(.*)$', '!\\1[0]') | list + compute_roles) | join(',') }}"
      tags:
        - system_upgrade
  when: compute_roles | length > 0

- name: Upgrade remaining Compute containers
  import_playbook: osp_deployment.yaml
  vars:
    config_generator_name: system-upgrade-computes
    deploy_name: container-update-computes
    deploy_mode: upgrade
    deploy_advanced_settings:
      # e.g limit: "!Compute[0],!ComputeHCI[0],Compute,ComputeHCI"
      limit: "{{ (compute_roles | map('regex_replace', '^(.*)$', '!\\1[0]') | list + compute_roles) | join(',') }}"
  when: compute_roles | length > 0
