---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: Set directory for generator yaml files
    set_fact:
      deploy_yamls_dir: "{{ working_yamls_dir }}/deploy"

  - name: show yaml output dir
    debug:
      msg: "yamls will be written to {{ deploy_yamls_dir }} locally"

  - name: Clean yaml dir
    file:
      state: absent
      path: "{{ deploy_yamls_dir }}/"

  - name: Create yaml dir
    file:
      path: "{{ deploy_yamls_dir }}"
      state: directory
      mode: '0755'

  - name: Lookup configVersion hash
    shell: >
      oc get -n openstack --sort-by {.metadata.creationTimestamp} osconfigversions -o json | jq -re .items[0].spec.hash
    register: config_version_cmd
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Set config_version fact
    set_fact:
      config_version: "{{ config_version_cmd.stdout }}"

  - name: Render templates to yaml dir
    template:
      src: "osp/deploy/{{ item }}.j2"
      dest: "{{ deploy_yamls_dir }}/{{ item }}"
      mode: '0644'
    with_items:
    - "openstackdeploy.yaml"

  - name: does the deployment already exist
    shell: >
      oc get -n openstack osdeploy default -o json --ignore-not-found
    environment:
      <<: *oc_env
    register: deploy_switch

  - name: Delete deployment (if it exists)
    shell: |
      set -e
      oc delete -n openstack osdeploy default
    environment:
      <<: *oc_env
    when: deploy_switch.stdout | length > 0

  - name: Start deployment
    shell: |
      set -e
      oc apply -n openstack -f "{{ deploy_yamls_dir }}/openstackdeploy.yaml"
    environment:
      <<: *oc_env
    when: deploy_switch.stdout | length == 0

  - name: wait for deployment to finish
    shell: |
      set -e
      oc wait -n openstack osdeploy default --for condition=Finished --timeout="{{ (default_timeout * 40)|int }}s"
    environment:
      <<: *oc_env
