---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: Set combined osp dict
    set_fact:
      osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

  - name: Accept rendered playbooks
    shell: |
      #!/bin/bash
      set -e
      oc rsh -n openstack openstackclient /home/cloud-admin/tripleo-deploy.sh -a
    environment: &oc_env
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: playbooks_accept

  - name: Run playbooks, deployment log at {{ working_log_dir }}/osp-deploy.log
    shell: |
      #!/bin/bash
      set -e
      oc rsh -n openstack openstackclient timeout {{ osp.deploy_timeout }} /home/cloud-admin/tripleo-deploy.sh -p > {{ working_log_dir }}/osp-deploy.log 2>&1
    environment:
      <<: *oc_env
    when: playbooks_accept.rc == 0

