---
# This is separated from virt_sriov.yaml so that a loop can be used with all the tasks below
# via an "include_tasks" task in that said file.  It is not intended to run stand-alone.
- name: Set VM name fact for dev-scripts
  set_fact:
    vm_name: "{{ item }}"
  when: not (ocp_ai | bool)

- name: Set VM name fact for AI
  set_fact:
    vm_name: "{{ item | replace('_','-') }}"
  when: (ocp_ai | bool)

- name: Stop {{ vm_name }} VM
  virt:
    name: "{{ vm_name }}"
    state: destroyed

- name: Dump {{ vm_name }} VM XML into temp file
  shell: |
    virsh dumpxml {{ vm_name }} > {{ xml_dir }}/{{ vm_name }}.xml

- name: Add ioapic QEMU driver to {{ vm_name }} VM XML
  lineinfile:
    path: "{{ xml_dir }}/{{ vm_name }}.xml"
    insertbefore: '</features>'
    line: "    <ioapic driver='qemu'/>"

- name: Add iommu device to {{ vm_name }} VM XML
  lineinfile:
    path: "{{ xml_dir }}/{{ vm_name }}.xml"
    insertbefore: '</devices>'
    line: "    <iommu model='intel'/>"

- name: Change machine type in {{ vm_name }} VM XML
  replace:
    path: "{{ xml_dir }}/{{ vm_name }}.xml"
    regexp: 'pc-q35-rhel8.2.0'
    replace: 'pc-q35-5.0'

- name: Change emulator location in {{ vm_name }} VM XML
  replace:
    path: "{{ xml_dir }}/{{ vm_name }}.xml"
    regexp: '/usr/libexec/qemu-kvm'
    replace: '/usr/libexec/qemu-system-x86_64'

- name: Update the {{ vm_name }} VM with the latest XML changes
  command: "virsh define {{ xml_dir }}/{{ vm_name }}.xml"

- name: Remove USB device from {{ vm_name }} VM
  command: "virsh detach-device {{ vm_name }} --file {{ xml_dir }}/usb-device.xml --config"
  register: usb_removed
  failed_when: usb_removed.stderr != "" and "device not found" not in usb_removed.stderr

- name: Remove OSP network device from {{ vm_name }} VM
  command: "virsh detach-device {{ vm_name }} --file {{ xml_dir }}/osp-interface-old.xml --config"
  register: interface_removed
  failed_when: interface_removed.stderr != "" and "device not found" not in interface_removed.stderr

- name: Attach e1000e OSP network device to {{ vm_name }} VM
  command: "virsh attach-device {{ vm_name }} --file {{ xml_dir }}/osp-interface-new.xml --config"