# Based on https://github.com/marketplace/actions/ansible-lint
name: Ansible lint github pipeline

on: [push, pull_request]

jobs:
  test:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint@v25.6.1
        with:
          requirements_file: ansible/requirements.yml
