# Based on https://github.com/marketplace/actions/ansible-lint
name: Ansible lint github pipeline

on: [push, pull_request]

jobs:
  test:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint-action@v6.0.2
