apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstack-proto
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstack-proto
subjects:
- kind: ServiceAccount
  name: openstack-proto
  namespace: openstack
